<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('buildings', function (Blueprint $table) {
            $table->id();
            $table->foreignId('player_id')->constrained('players')->onDelete('cascade');
            $table->string('building_name')->comment('Name of the building');
            $table->integer('position')->comment('Position of the building on the map');
            $table->integer('level')->default(1)->comment('Level of the building');
            $table->string('status')->default('active')->comment('Status of the building, e.g., active, under construction, destroyed');
            $table->integer('cost')->default(0)->comment('Cost of building or upgrading, e.g., in resources like wood, stone, or gold');
            $table->integer('production_rate')->default(0)->comment('Rate at which the building produces resources or provides benefits');
            $table->integer('income')->default(0)->comment('Income generated by the building, if applicable, e.g., from taxes or resource production');
            $table->integer('max_level')->default(10)->comment('Maximum level the building can be upgraded to');
            $table->integer('upgrade_cost')->default(0)->comment('Cost to upgrade the building to the next level');
            $table->integer('upgrade_time')->default(0)->comment('Time required to upgrade the building to the next level');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('buildings');
    }
};
